### PR TITLE
Fix generated sql so it's a valid MySQL statement

### PR DESCRIPTION
**Pull request by reynardmh**
generated SQL from toString doesn't create a valid MySQL statement for table_name.column_name

```
# invalid syntax: 
`table_name.column_name`
# The correct syntax should be: 
`table_name`.`column_name`
```

### CODE REVIEW

**Comment by mistic100** [comment]
Please do not commit built files.

**Comment by mistic100** [comment]
@reynardmh

**Comment by reynardmh** [comment]
Sorry, I completely forgot to update this, will try to do it this weekend.

**Comment by reynardmh** [comment]
ok, how about this?

**Pull request merged**
